display_name: demo
package_name: demo

maintainer:
  name: Rahul BHarti
  email: rahul.bharti@kreatetechnologies.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - mpv

essential: false

icon: linux/assets/menu.png

postuninstall_scripts:
  - echo "Sorry to see you go."

keywords:
  - API
  - API Client

generic_name: API Client

categories:
  - Development
  - Utility

startup_notify: true
